### ISSUE TITLE
Introducing face colors

### ISSUE THREAD

**Issue by kovacsv** [paireks/dotbim#11]
### Problem statement

Right now that is a big limitation that one element can have only one color. It can be workarounded if you create multiple elements sorted by color, but that causes illogical separation of the element, and it's also not clear where metadata should be stored.

In most of the cases it's not possible to simplify an element to use only one color. For example the outside and inside color of a wall is often different. This limitation is even more serious in case of doors or windows, because these elements usually have different color for frame and glass, and the latter is usually transparent.

### Proposed solution

I'd like to propose the following solution:
- Bump the version to `1.1.0` signaling that the new version is backward compatible.
- Add a new key to elements called `face_colors`. This can be an array integer of values that will contain r, g, b, a values for each face, int the same order as faces listed in the `indices` array.

The `color` should still remain mandatory, so viewers and importers that not yet support face colors will work without a problem. This solution is still very easy to parse, but I think it adds great value to the format.

### Example

```diff
{
-  "schema_version": "1.0.0",
+  "schema_version": "1.1.0",
  "meshes": [
    {
      "mesh_id": 0,
      "coordinates": [ 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0 ],
      "indices": [ 0, 1, 2, 0, 2, 3 ]
    }
  ],
  "elements": [
    {
      "mesh_id": 0,
      "vector": { "x": 0.0, "y": 0.0, "z": 0.0},
      "rotation": { "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0 },
      "guid": "9f61b565-06a2-4bef-8b72-f37091ab54d6",
      "type": "Brick",
      "color": { "r": 255, "g": 0, "b": 0, "a": 255 },
+      "face_colors" : [ 255, 0, 0, 255, 0, 255, 0, 255 ]
      "info": {
        "Name": "Colored Element"
      }
    }
  ],
  "info": {
    "Author": "Viktor Kovacs"
  }
}

```

**Comment by paireks** [comment]
Hey Viktor!

This is good idea, and I agree with the fact that this is big limitation. The background of this decision was the fact, that some of the software can have some issues to color a mesh of one element this way. 

E.g. in Rhino you can color one mesh, but not using faces, but only using vertices: https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Collections_MeshVertexColorList_SetColor.htm
The effect of such colouring is compeletely different. To color it by faces in Rhino people are exploding the mesh into separate triangles, which could be problematic as we want to treat this as one.
I was also a bit worried about tools for structure modelling e.g. Tekla https://developer.tekla.com/tekla-structures/api/22/15479

Thing is I try to make sure that all software can support 100% of file format features, and I was worried that some of them can't store element with different color meshes.

**Comment by paireks** [comment]
After some research conclusion is that multicolor meshes needs to be supported, and actually Rhino should be able to at least read it, as well as Tekla probably.

**Comment by paireks** [comment]
To provide multicolor elements extension with an optional "face_colors" tag has been created: https://github.com/paireks/dotbim-extensions-multicolor
