### ISSUE TITLE
Mesh normal problem, Grasshopper plugin

### ISSUE THREAD

**Issue by seghier** [paireks/dotbim#29]
Hi
i download this file and import it with Grasshopper then bake the meshes and i notice that there is a problem with normals
Can you check it?

https://3dviewer.net/#model=https://raw.githubusercontent.com/paireks/dotbim/master/test/ExampleFiles/TestFilesFromBlender/Site%20plan%201.bim

![image](https://github.com/paireks/dotbim/assets/6026588/a4f12b99-8afb-4894-a4f0-087768061597)

**Comment by seghier** [comment]
Can we have an option to fix the normals? because in Rhino it must done manually.
Unweld
Explode
Flip direction 
Join

**Comment by paireks** [comment]
I think we shouldn't fix meshes automatically during import. We should import a file exactly as it looks like. Otherwise we will have different outputs in different software.

**Comment by seghier** [comment]
Mesh flip fix the issue but there is no way to detect normal direction and fix it in Rhino

**Comment by paireks** [comment]
Yeah you're right. But even if there would be something that would detect and fix - I won't use it automatically.

We can fix this specific model manually and update it, but I think it is ok as it is, there are few more models there that also have flipped faces. Some of them are even on purpose to check the behaviour in different viewers.
