### ISSUE TITLE
Provide test files for conformance testing

### ISSUE THREAD

**Issue by kovacsv** [paireks/dotbim#9]
It would be much easier to write an importer if there would be some test files available with different important scenarios (like transformations or reusing a mesh with different colors).

**Comment by paireks** [comment]
Thank you for that comment, I uploaded right now few test files from different sources here: https://github.com/paireks/dotbim/tree/master/test/ExampleFiles

Each test file has it's own .png to check visually if it's ok. All of them are quite simple, but checks various things. I think later it would be great to add some big one e.g. for performance check.

**Comment by kovacsv** [comment]
I've tried this one: https://github.com/paireks/dotbim/blob/master/test/ExampleFiles/TestFilesFromC%23/Cubes.bim

The png looks like this:
![Cubes](https://user-images.githubusercontent.com/2034315/154800213-6754724c-f5a2-433f-8303-d24523496823.png)

But in the official viewer it looks really strange:
![image](https://user-images.githubusercontent.com/2034315/154800238-07e30b72-abc4-4e76-962c-eaeff0c897a8.png)

I think that the rotation value is not correct in that file.

**Comment by paireks** [comment]
Yeah, you're right, rotation values are probably wrong, I will change this file

**Comment by paireks** [comment]
I've changed this example already. For rotation checks you can use this example: https://github.com/paireks/dotbim/blob/master/test/ExampleFiles/TestFilesFromGh/BricksRotated.bim
